add required dependencies ; to avoid
java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError:
	at org.exist.xquery.XQueryContext.getUserFromHttpSession(XQueryContext.java:2246)
	at org.exist.xquery.XQueryContext.prepareForExecution(XQueryContext.java:588)